"""Initial Migration

Revision ID: 813d200fc8bc
Revises: 
Create Date: 2019-09-24 10:49:09.512846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813d200fc8bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'categoryname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('categoryname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'category')
    # ### end Alembic commands ###
