"""Initial Migration

Revision ID: d6659fec8215
Revises: da03c7734b6b
Create Date: 2019-09-23 16:13:13.622371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6659fec8215'
down_revision = 'da03c7734b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'pitchDesc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('pitchDesc', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
